import { useEffect, useState } from "react";
import axios from "axios";
import {
  FaBrain, FaSyncAlt, FaCheckCircle, FaExclamationTriangle,
  FaDatabase, FaChartBar, FaTh,
} from "react-icons/fa";
import Navbar from "../components/Navbar";

// ── colour helpers ────────────────────────────────────────────────
function pct(v) { return v != null ? `${(v * 100).toFixed(2)}%` : "—"; }

function scoreColor(v) {
  if (v == null) return "text-slate-400";
  if (v >= 0.90) return "text-emerald-400";
  if (v >= 0.75) return "text-yellow-400";
  return "text-red-400";
}

function Bar({ value, color = "#22d3ee" }) {
  return (
    <div className="w-full bg-slate-800 rounded-full h-1.5 mt-1">
      <div
        className="h-1.5 rounded-full transition-all duration-500"
        style={{ width: `${(value * 100).toFixed(1)}%`, backgroundColor: color }}
      />
    </div>
  );
}

const CLASS_COLORS = {
  Normal:           "#34d399",
  Bearing_Wear:     "#fb923c",
  Overheating_Risk: "#facc15",
  Overloaded:       "#f97316",
  Critical:         "#f87171",
};

// ─────────────────────────────────────────────────────────────────
function ModelResults() {
  const [data, setData]     = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]   = useState(null);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await axios.get("http://127.0.0.1:8000/api/training-results");
      setData(res.data);
    } catch (e) {
      setError(e.response?.data?.error ?? "Could not reach the backend.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Navbar />

      {/* ── Header ──────────────────────────────────────── */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-purple-950/40 via-slate-950 to-slate-950" />
        <div
          className="absolute inset-0"
          style={{
            backgroundImage:
              "radial-gradient(circle at 1px 1px, rgba(148,163,184,0.05) 1px, transparent 0)",
            backgroundSize: "40px 40px",
          }}
        />
        <div className="relative max-w-7xl mx-auto px-6 py-14 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-3 mb-3">
              <div className="w-10 h-10 bg-purple-600/15 border border-purple-500/30 rounded-xl flex items-center justify-center">
                <FaBrain className="text-purple-400" />
              </div>
              <h1 className="text-4xl font-black tracking-tight">
                Model <span className="text-purple-400">Results</span>
              </h1>
            </div>
            <p className="text-slate-500 text-sm">
              Last training run — generated by <code className="text-slate-400 bg-slate-800 px-1.5 py-0.5 rounded text-xs">retrain.py</code>
            </p>
          </div>
          <button
            onClick={load}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium
                       bg-slate-800 border border-slate-700 text-slate-300
                       hover:bg-slate-700 transition-all disabled:opacity-50 self-start sm:self-auto"
          >
            <FaSyncAlt className={loading ? "animate-spin" : ""} /> Refresh
          </button>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-6 pb-20 space-y-8">

        {/* ── Loading / error / empty states ──────────── */}
        {loading && (
          <div className="flex items-center justify-center py-32 gap-3 text-slate-500 text-sm">
            <FaSyncAlt className="animate-spin" /> Loading results…
          </div>
        )}

        {!loading && error && (
          <div className="flex flex-col items-center justify-center py-32 gap-3 text-slate-600">
            <FaExclamationTriangle className="text-3xl text-amber-500" />
            <p className="text-slate-400 font-semibold">{error}</p>
            <p className="text-slate-600 text-sm text-center max-w-sm">
              Run <code className="bg-slate-800 text-slate-300 px-2 py-0.5 rounded text-xs">python retrain.py</code> from the
              <code className="bg-slate-800 text-slate-300 px-2 py-0.5 rounded text-xs ml-1">backend/</code> folder
              to generate results.
            </p>
          </div>
        )}

        {!loading && data && (
          <>
            {/* ── Meta row ──────────────────────────────── */}
            <div className="flex flex-wrap gap-3 text-xs text-slate-500">
              <span className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-1.5">
                Trained at <span className="text-slate-300 font-semibold">{data.trained_at}</span>
              </span>
              <span className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-1.5">
                Total rows <span className="text-slate-300 font-semibold">{data.dataset?.total_rows?.toLocaleString()}</span>
                <span className="mx-1 text-slate-700">·</span>
                Train <span className="text-emerald-400 font-semibold">{data.dataset?.train_rows?.toLocaleString()}</span>
                <span className="mx-1 text-slate-700">/</span>
                Test <span className="text-blue-400 font-semibold">{data.dataset?.test_rows?.toLocaleString()}</span>
                <span className="text-slate-600 ml-1">(80 / 20)</span>
              </span>
              <span className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-1.5">
                Real-world rows <span className="text-purple-400 font-semibold">{data.dataset?.history_rows?.toLocaleString()}</span>
              </span>
            </div>

            {/* ── Overall accuracy cards ─────────────────── */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              <OverallCard label="Accuracy"    value={data.accuracy}          color="text-emerald-400" />
              <OverallCard label="Precision"   value={data.macro_precision}   color="text-blue-400"   />
              <OverallCard label="Recall"      value={data.macro_recall}      color="text-cyan-400"   />
              <OverallCard label="Specificity" value={data.macro_specificity} color="text-purple-400" />
            </div>

            {data.old_accuracy != null && (
              <div className={`flex items-center gap-3 rounded-xl px-5 py-3 text-sm border
                ${data.accuracy >= data.old_accuracy
                  ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-300"
                  : "bg-amber-500/10  border-amber-500/20  text-amber-300"}`}
              >
                {data.accuracy >= data.old_accuracy
                  ? <FaCheckCircle />
                  : <FaExclamationTriangle />}
                <span>
                  Previous model accuracy was <strong>{pct(data.old_accuracy)}</strong>.
                  {data.accuracy >= data.old_accuracy
                    ? ` New model improved by ${((data.accuracy - data.old_accuracy) * 100).toFixed(2)}%.`
                    : ` New model dropped by ${((data.old_accuracy - data.accuracy) * 100).toFixed(2)}% — consider discarding.`}
                </span>
              </div>
            )}

            {/* ── Per-class metrics table ────────────────── */}
            <div>
              <SectionTitle icon={<FaChartBar />} title="Per-Class Metrics" />
              <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden">
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-slate-800 text-slate-500 text-xs uppercase tracking-wider">
                        {["Fault Class", "Precision", "Recall", "Specificity", "F1-Score", "Support"].map((h) => (
                          <th key={h} className="px-5 py-3 text-left font-semibold whitespace-nowrap">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {data.classes?.map((cls) => {
                        const m = data.per_class?.[cls];
                        const color = CLASS_COLORS[cls] ?? "#94a3b8";
                        return (
                          <tr key={cls} className="border-b border-slate-800/60 hover:bg-slate-800/30 transition-colors">
                            <td className="px-5 py-4">
                              <span
                                className="text-xs font-bold border rounded-md px-2.5 py-1"
                                style={{ color, borderColor: color + "55", backgroundColor: color + "18" }}
                              >
                                {cls.replace("_", " ")}
                              </span>
                            </td>
                            <MetricCell value={m?.precision} />
                            <MetricCell value={m?.recall} />
                            <MetricCell value={m?.specificity} />
                            <MetricCell value={m?.f1_score} />
                            <td className="px-5 py-4 text-slate-400 font-mono">{m?.support}</td>
                          </tr>
                        );
                      })}

                      {/* Macro averages row */}
                      <tr className="bg-slate-800/30">
                        <td className="px-5 py-3 text-slate-400 text-xs font-bold uppercase tracking-wider">Macro Avg</td>
                        <MacroCell value={data.macro_precision} />
                        <MacroCell value={data.macro_recall} />
                        <MacroCell value={data.macro_specificity} />
                        <MacroCell value={data.macro_f1} />
                        <td className="px-5 py-3" />
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {/* ── Confusion matrix ──────────────────────── */}
            <div>
              <SectionTitle icon={<FaTh />} title="Confusion Matrix  (row = actual · col = predicted)" />
              <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-auto p-5">
                <ConfusionMatrix cm={data.confusion_matrix} classes={data.classes} />
              </div>
            </div>

            {/* ── Feature importances ───────────────────── */}
            <div>
              <SectionTitle icon={<FaDatabase />} title="Feature Importances" />
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
                {data.feature_importances &&
                  Object.entries(data.feature_importances)
                    .sort(([, a], [, b]) => b - a)
                    .map(([feat, imp]) => (
                      <div key={feat}>
                        <div className="flex items-center justify-between text-sm mb-1">
                          <span className="text-slate-300 font-mono">{feat}</span>
                          <span className={`font-bold ${scoreColor(imp)}`}>{(imp * 100).toFixed(2)}%</span>
                        </div>
                        <Bar value={imp} color={imp > 0.2 ? "#a78bfa" : imp > 0.1 ? "#60a5fa" : "#475569"} />
                      </div>
                    ))}
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ── Sub-components ────────────────────────────────────────────────

function SectionTitle({ icon, title }) {
  return (
    <div className="flex items-center gap-3 mb-4">
      <span className="text-purple-400 text-sm">{icon}</span>
      <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500">{title}</h2>
      <div className="flex-1 h-px bg-slate-800" />
    </div>
  );
}

function OverallCard({ label, value, color }) {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5">
      <p className="text-slate-500 text-xs mb-2">{label}</p>
      <p className={`text-3xl font-black ${color}`}>{pct(value)}</p>
      <Bar value={value ?? 0} color={color === "text-emerald-400" ? "#34d399"
        : color === "text-blue-400" ? "#60a5fa"
        : color === "text-cyan-400" ? "#22d3ee"
        : "#a78bfa"} />
    </div>
  );
}

function MetricCell({ value }) {
  return (
    <td className={`px-5 py-4 font-semibold ${scoreColor(value)}`}>
      {pct(value)}
    </td>
  );
}

function MacroCell({ value }) {
  return (
    <td className={`px-5 py-3 font-bold text-sm ${scoreColor(value)}`}>
      {pct(value)}
    </td>
  );
}

function ConfusionMatrix({ cm, classes }) {
  if (!cm || !classes) return null;

  const maxVal = Math.max(...cm.flat());

  return (
    <div className="overflow-x-auto">
      <table className="text-xs border-separate border-spacing-1">
        <thead>
          <tr>
            <th className="text-slate-600 text-left pr-3 pb-2 font-normal w-28">actual ↓ pred →</th>
            {classes.map((c) => (
              <th key={c} className="text-slate-400 font-semibold pb-2 px-2 text-center whitespace-nowrap">
                {c.replace("_", " ")}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {cm.map((row, i) => (
            <tr key={i}>
              <td className="text-slate-400 font-semibold pr-3 py-1 whitespace-nowrap">
                {classes[i].replace("_", " ")}
              </td>
              {row.map((val, j) => {
                const isDiag   = i === j;
                const opacity  = maxVal > 0 ? val / maxVal : 0;
                const bg       = isDiag
                  ? `rgba(52,211,153,${0.15 + opacity * 0.5})`
                  : val > 0
                  ? `rgba(248,113,113,${0.1 + opacity * 0.4})`
                  : "rgba(30,41,59,0.8)";
                return (
                  <td
                    key={j}
                    className="text-center font-bold rounded-lg py-2 px-4 min-w-[60px]"
                    style={{ backgroundColor: bg, color: isDiag ? "#34d399" : val > 0 ? "#fca5a5" : "#475569" }}
                  >
                    {val}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ModelResults;
